version: "1.0"
services:
  db:
    image: postgis/postgis:17-3.5
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks:
      - net
    healthcheck:
      test: pg_isready -q -d vaisala -U postgres
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5500:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vaisala

  backend:
    build:
      dockerfile: backend/Dockerfile
      args:
        RUN_MODE: "start"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    command: "npm start"
    environment:
      DB_PORT: 5432
      DB_HOST: db

networks:
  net:
    driver: bridge
