version: "1.0"
services:
  db:
    image: postgis/postgis:17-3.5
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vaisala
    healthcheck:
      test: pg_isready -q -d vaisala -U postgres
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s
  backend:
    build:
      dockerfile: ./Dockerfile
    command: "npm test"
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
