services:
  db:
    extends:
      file: compose/database.yml
      service: db
  backend:
    build:
      dockerfile: ./Dockerfile
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    command: "npm start"
    environment:
      DB_PORT: 5432
      DB_HOST: db

networks:
  net:
    driver: bridge
